### ISSUE TITLE
some nodes are missing

### ISSUE THREAD

**Issue by UweW** [CODAIT/node-red-contrib-model-asset-exchange#39]
Hi,
different to the description the scene-classifier and image-segmenter nodes are not included.
best regards
Uwe

**Comment by zuhito** [comment]
I think that you are using the old version of the node. Could you upgrade the node on User Settings UI?

<img width="1280" alt="updatenode" src="https://user-images.githubusercontent.com/6851138/54080725-a7dd3600-4339-11e9-89c2-1f87a294728a.png">

**Comment by UweW** [comment]
Hi,
I did a complete reinstall of the modul and I am wondering that it still needs an update to get the actual version.
The update fails when I use the ui. Using  "npm update ..."  the update works and after restart the missing nodes are there.
Thank's a lot

Uwe
