### ISSUE TITLE
Update Response Payload for Multiple-Entity Models

### ISSUE THREAD

**Issue by kastentx** [CODAIT/node-red-contrib-model-asset-exchange#45]
Following the format of the `facial-emotion-classifier` node, update the response payload for models that have the potential for predictions on more than one entity.

this includes:
* object-detector
* facial-recognizer
* facial-age-estimator
* image-segmenter
* human-pose-estimator

Currently, the first prediction is returned as a string in `msg.payload`.

This change would convert `msg.payload` to an object with two properties: `entitiesDetected` which holds a number value, and `prediction` which holds an array containing the same number of predictions.

For example, a response with one prediction would look like: 

```javascript
msg.payload = {
  entitiesDetected: 1,
  prediction: ['person']
}
```

While a response with multiple entities/predictions would look like:

```javascript
msg.payload = {
  entitiesDetected: 3,
  prediction: ['person', 'dog', 'chair']
}
```

**Comment by zuhito** [comment]
I'd like to respect CODAIT team opinion.

I intentionally used the first result in predicted data. When users use the MAX nodes at the first time, they will easily feel the result good if the output data is simple (If the data has JSON structure, users need to find the result). And it is easy to connect to other Node-RED nodes (e.g. Translation API) if the output data is just string. In the current implementation, msg.details has all result from IBM MAX container. Therefore, if users want to use not only the first result but also other results, they can use `msg.details` to handle the data. (Current problem is that there's no documentation about `msg.details`.)

To realize both opinions, I think that pull-down menu on node property to select an output format (e.g. first result only, all results) like file-in node may be a candidate solution.

<img width="1280" alt="file-in" src="https://user-images.githubusercontent.com/6851138/54922796-3eba0d00-4f4c-11e9-96ba-65cef17a0e46.png">

**Comment by kastentx** [comment]
After more feedback from the Node-RED community we've decided not to pursue these changes anymore, and will instead standardize the existing format.

**Comment by zuhito** [comment]
Thank you for your understanding! 🥇
