### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by ptitzler** [CODAIT/node-red-contrib-model-asset-exchange#8]
- Add build status badge
  `[![Build Status](https://travis-ci.org/CODAIT/node-red-contrib-model-asset-exchange.svg?branch=master)](https://travis-ci.org/CODAIT/node-red-contrib-model-asset-exchange)`
- Add npm package badge
  `[![npm version](https://badge.fury.io/js/node-red-contrib-model-asset-exchange.svg)](https://badge.fury.io/js/node-red-contrib-model-asset-exchange)`

...

**Comment by kastentx** [comment]
closed by #9
